# Generated by Django 3.2.13 on 2022-11-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='link',
            new_name='card_url',
        ),
        migrations.RenameField(
            model_name='data',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='data',
            name='brand',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='card_image',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
        migrations.AddField(
            model_name='data',
            name='card_type',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='fee',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_name', models.CharField(max_length=20)),
                ('benefit_content', models.TextField()),
                ('benefit_detail', models.TextField()),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.data')),
            ],
        ),
    ]
