# Generated by Django 3.2.13 on 2022-11-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20221128_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='card_image',
            field=models.URLField(),
        ),
    ]
