# Generated by Django 3.2.13 on 2022-11-29 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20221129_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='card_url',
        ),
    ]
